apiVersion: v1
kind: Service
metadata:
  name: codetweet-db
  labels:
    run: codetweet-db
spec:
  ports:
  - port: 1433
    protocol: TCP
  selector:
    run: codetweet-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: codetweet-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: codetweet-db
    spec:
      containers:
      - name: codetweet-db
        image: microsoft/mssql-server-windows-express
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: sa_password
          value: PasswordF0rP@blish
      nodeSelector:
        beta.kubernetes.io/os: windows
      restartPolicy: Always
